package com.dbperf.report.service;

import com.dbperf.ai.AiReportSummary;
import com.dbperf.analyzer.dto.AnalysisHistoryItem;
import com.dbperf.dashboard.dto.DashboardResponse.ScoreFactor;
import com.dbperf.metrics.dto.QueryStat;
import com.dbperf.metrics.dto.SnapshotSummaryResponse;
import com.dbperf.metrics.dto.TableStat;
import com.dbperf.report.dto.ReportModel;
import org.springframework.stereotype.Component;

import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Renders the report as strict XHTML (openhtmltopdf parses XML, so every
 * tag is closed and all dynamic values go through {@link #esc}).
 */
@Component
public class ReportHtmlRenderer {

    private static final DateTimeFormatter TIMESTAMP =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'").withZone(ZoneOffset.UTC);
    private static final DateTimeFormatter SHORT_TIME =
            DateTimeFormatter.ofPattern("MM-dd HH:mm").withZone(ZoneOffset.UTC);

    public String render(ReportModel model) {
        StringBuilder html = new StringBuilder();
        html.append("""
                <?xml version="1.0" encoding="UTF-8"?>
                <html xmlns="http://www.w3.org/1999/xhtml">
                <head>
                <style>
                  @page { size: A4; margin: 22mm 16mm; }
                  body { font-family: Helvetica, Arial, sans-serif; font-size: 10pt; color: #1f2937; margin: 0; }
                  h1 { font-size: 20pt; margin: 0 0 2pt 0; color: #312e81; }
                  h2 { font-size: 13pt; color: #4338ca; border-bottom: 1.5pt solid #e0e7ff; padding-bottom: 3pt; margin: 18pt 0 8pt 0; page-break-after: avoid; }
                  p { line-height: 1.45; margin: 5pt 0; }
                  table { width: 100%; border-collapse: collapse; margin: 6pt 0; }
                  th { background: #eef2ff; color: #3730a3; text-align: left; padding: 4pt 6pt; font-size: 8.5pt; }
                  td { padding: 4pt 6pt; border-bottom: 0.5pt solid #e5e7eb; font-size: 8.5pt; vertical-align: top; }
                  .muted { color: #6b7280; }
                  .mono { font-family: Courier, monospace; font-size: 8pt; }
                  .sql { background: #f5f3ff; border: 0.5pt solid #ddd6fe; border-radius: 3pt; padding: 6pt; font-family: Courier, monospace; font-size: 8pt; margin: 4pt 0; white-space: pre-wrap; }
                  .chip { display: inline-block; border-radius: 8pt; padding: 1pt 7pt; font-size: 8pt; font-weight: bold; }
                  .chip-high { background: #fee2e2; color: #b91c1c; }
                  .chip-medium { background: #fef3c7; color: #b45309; }
                  .chip-low { background: #dbeafe; color: #1d4ed8; }
                  .score-box { border: 1.5pt solid #e0e7ff; border-radius: 6pt; padding: 10pt 14pt; margin: 10pt 0; }
                  .score-number { font-size: 30pt; font-weight: bold; }
                  .grade-good { color: #15803d; }
                  .grade-mid { color: #b45309; }
                  .grade-bad { color: #b91c1c; }
                  .bar-track { background: #e5e7eb; height: 6pt; width: 100%; }
                  .bar-fill { background: #6366f1; height: 6pt; }
                  .finding { margin: 3pt 0; }
                  .action { border-left: 2.5pt solid #6366f1; padding: 2pt 0 2pt 8pt; margin: 8pt 0; page-break-inside: avoid; }
                  .footer { margin-top: 20pt; padding-top: 6pt; border-top: 0.5pt solid #e5e7eb; font-size: 7.5pt; color: #9ca3af; }
                </style>
                </head>
                <body>
                """);

        header(html, model);
        healthSection(html, model);
        aiSummarySection(html, model.summary());
        actionPlanSection(html, model.summary().actionPlan());
        topQueriesSection(html, model.latest().topQueries());
        tableStatsSection(html, model.latest().tableStats());
        trendSection(html, model.history());
        analysesSection(html, model.recentAnalyses());

        html.append("""
                <div class="footer">
                Generated by DBInsightX — AI Database Performance Engineer. AI content produced by %s and \
                grounded in metrics collected from the target database; review recommendations before \
                applying them to production.
                </div>
                </body>
                </html>
                """.formatted(esc(model.aiModel())));
        return html.toString();
    }

    private void header(StringBuilder html, ReportModel model) {
        html.append("<h1>Database Optimization Report</h1>");
        html.append("<p class=\"muted\">%s — database <b>%s</b> on %s<br/>Generated %s</p>"
                .formatted(esc(model.connectionName()), esc(model.databaseName()),
                        esc(model.host()), TIMESTAMP.format(model.generatedAt())));
    }

    private void healthSection(StringBuilder html, ReportModel model) {
        int score = model.health().score();
        String grade = model.health().grade();
        String gradeClass = score >= 75 ? "grade-good" : score >= 50 ? "grade-mid" : "grade-bad";
        html.append("<div class=\"score-box\">");
        html.append("<span class=\"score-number %s\">%d</span> <b class=\"%s\">/100 — grade %s</b>"
                .formatted(gradeClass, score, gradeClass, esc(grade)));
        List<ScoreFactor> factors = model.health().factors();
        if (factors.isEmpty()) {
            html.append("<p class=\"muted\">No deductions — all monitored signals are healthy.</p>");
        } else {
            html.append("<table><tr><th>Deduction</th><th>Penalty</th></tr>");
            for (ScoreFactor factor : factors) {
                html.append("<tr><td>%s</td><td>-%d</td></tr>"
                        .formatted(esc(factor.label()), factor.penalty()));
            }
            html.append("</table>");
        }
        html.append("</div>");
    }

    private void aiSummarySection(StringBuilder html, AiReportSummary summary) {
        html.append("<h2>Executive Summary</h2>");
        for (String paragraph : summary.executiveSummary().split("\n\n+")) {
            html.append("<p>%s</p>".formatted(esc(paragraph.strip())));
        }
        if (summary.keyFindings() != null && !summary.keyFindings().isEmpty()) {
            html.append("<h2>Key Findings</h2>");
            for (String finding : summary.keyFindings()) {
                html.append("<p class=\"finding\">&#8226; %s</p>".formatted(esc(finding)));
            }
        }
    }

    private void actionPlanSection(StringBuilder html, List<AiReportSummary.ActionItem> actions) {
        if (actions == null || actions.isEmpty()) {
            return;
        }
        html.append("<h2>Prioritized Action Plan</h2>");
        int index = 1;
        for (AiReportSummary.ActionItem action : actions) {
            html.append("<div class=\"action\">");
            html.append("<p><b>%d. %s</b> <span class=\"chip %s\">%s</span></p>"
                    .formatted(index++, esc(action.title()), chipClass(action.priority()),
                            esc(action.priority() == null ? "INFO" : action.priority())));
            html.append("<p>%s</p>".formatted(esc(action.detail())));
            if (action.sql() != null && !action.sql().isBlank()) {
                html.append("<div class=\"sql\">%s</div>".formatted(esc(action.sql())));
            }
            if (action.estimatedImpact() != null && !action.estimatedImpact().isBlank()) {
                html.append("<p class=\"muted\">Estimated impact: %s</p>".formatted(esc(action.estimatedImpact())));
            }
            html.append("</div>");
        }
    }

    private void topQueriesSection(StringBuilder html, List<QueryStat> queries) {
        html.append("<h2>Top Queries by Total Time</h2>");
        html.append("<table><tr><th>Query</th><th>Calls</th><th>Mean</th><th>Total</th><th>Cache hit</th></tr>");
        for (QueryStat q : queries.stream().limit(12).toList()) {
            html.append("<tr><td class=\"mono\">%s</td><td>%d</td><td>%.1f ms</td><td>%.0f ms</td><td>%.0f%%</td></tr>"
                    .formatted(esc(truncate(q.query().replaceAll("\\s+", " "), 160)),
                            q.calls(), q.meanTimeMs(), q.totalTimeMs(), q.hitRatio() * 100));
        }
        html.append("</table>");
    }

    private void tableStatsSection(StringBuilder html, List<TableStat> tables) {
        html.append("<h2>Table Access Patterns</h2>");
        html.append("<table><tr><th>Table</th><th>Live rows</th><th>Seq scans</th><th>Rows read sequentially</th><th>Index scans</th></tr>");
        for (TableStat t : tables) {
            html.append("<tr><td class=\"mono\">%s</td><td>%,d</td><td>%d</td><td>%,d</td><td>%d</td></tr>"
                    .formatted(esc(t.tableName()), t.liveRows(), t.seqScans(), t.seqTupRead(), t.idxScans()));
        }
        html.append("</table>");
    }

    private void trendSection(StringBuilder html, List<SnapshotSummaryResponse> history) {
        if (history.size() < 2) {
            return;
        }
        html.append("<h2>Recent Snapshot Trend</h2>");
        html.append("<table><tr><th>Captured</th><th>Cache hit ratio</th><th></th><th>Active</th><th>Blocked</th><th>Waiting locks</th></tr>");
        // oldest first so the trend reads left-to-right in time
        for (SnapshotSummaryResponse s : history.reversed()) {
            double ratio = s.cacheHitRatio() == null ? 0 : s.cacheHitRatio();
            html.append(("<tr><td>%s</td><td>%s</td>"
                    + "<td style=\"width:90pt\"><div class=\"bar-track\"><div class=\"bar-fill\" style=\"width:%.0f%%\"></div></div></td>"
                    + "<td>%d</td><td>%d</td><td>%d</td></tr>")
                    .formatted(SHORT_TIME.format(s.capturedAt()),
                            s.cacheHitRatio() == null ? "n/a" : "%.1f%%".formatted(ratio * 100),
                            ratio * 100, s.activeSessions(), s.blockedSessions(), s.waitingLocks()));
        }
        html.append("</table>");
    }

    private void analysesSection(StringBuilder html, List<AnalysisHistoryItem> analyses) {
        if (analyses.isEmpty()) {
            return;
        }
        html.append("<h2>Recent Query Analyses</h2>");
        for (AnalysisHistoryItem item : analyses) {
            html.append("<p><span class=\"muted\">%s</span> — <span class=\"mono\">%s</span><br/>%s</p>"
                    .formatted(TIMESTAMP.format(item.createdAt()), esc(item.sqlSnippet()),
                            esc(item.summary() == null ? "" : item.summary())));
        }
    }

    private static String chipClass(String priority) {
        return switch (priority == null ? "" : priority.toUpperCase()) {
            case "HIGH" -> "chip-high";
            case "MEDIUM" -> "chip-medium";
            default -> "chip-low";
        };
    }

    private static String truncate(String text, int max) {
        return text.length() <= max ? text : text.substring(0, max) + "…";
    }

    static String esc(String text) {
        if (text == null) {
            return "";
        }
        return text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
